***In Turbine how do you  detect when an exception has occurred in your flow under test without crashing your test?***

<div class="hint">
  awaitError -Turbine
</div>
